### ISSUE TITLE
Multi-Dataset Tabs

### ISSUE THREAD

**Issue by danich1** [greenelab/word-lapse#25]
Currently this project works with models that are trained on abstracts; however, abstracts can only provide so much context. Ideally, everyone would be more excited if we can extend this to incorporate full-text and also preprints. I have full text running as we speak, but it will take  at least up until the weekend to get those models fully trained.  

In terms of incorporating this idea the following additions will need to be implemented:

- [ ] Front end 
  - [ ]  a tab to indicate the user with category of models are going to be used: PubMed abstracts, PubMed full-text or biorxiv/medrxiv 
  - [ ] a way to indicate to the backend which model to use
- [ ] Backend
  - [ ] A way to gather word neighbors depending on the model context  
    - may have a RAM issue with full-text and we can discuss solutions around it. (Quick fix is to precompute X amount of neighbors and then just index that)
  - [ ] A way to gather detected changepoints depending on model context 
    - simple dict lookup not too bad

**Comment by vincerubinetti** [comment]
For the frontend, it seems like all we need is a [dropdown](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select) next to the search box that controls the model, and that passes the appropriate flag to the backend. That should be very quick to add, so @falquaddoomi just let me know when the backend supports this.
