### ISSUE TITLE
Auto-Complete Feature Request

### ISSUE THREAD

**Issue by danich1** [greenelab/word-lapse#27]
I was thinking about having an auto complete feature so when users attempt to type in an entry they could be suggested data-points to query. Looking online there seems to be a [data structure](https://www.geeksforgeeks.org/auto-complete-feature-using-trie/) that could handle the backend for this feature. Ideally, this would be populate this model using every unique token found and then let the model suggest entries for a user. Main question here is it possible? Also, is this even worth exploring?

**Comment by falquaddoomi** [comment]
Sure, it's doable. I assume you'll want to merge the vocabularies for all the year models into a set (i.e., no duplicates), right? I did a little back-of-the-envelope run on the new dataset (i.e., 2010-2020), and there are 203,264 unique tokens, well within what I'd expect to be autocomplete-able.
