### ISSUE TITLE
Will the models be versioned? Multiple models in the same year?

### ISSUE THREAD

**Issue by staylorx** [greenelab/word-lapse#3]
Hi @danich1. Looking at your model mapping, I'm looking at the regex for the model file in the form `<year>_<some_integer>.model`. Are you planning on having more than a single year model file? E.g., 2013_0.model, 2013_1.model, etc?

**Comment by danich1** [comment]
Yes. Each year has ten different models due variation with an NLP model. I set the code to only use one model, but it will be adapted into using all the available models.
